### ISSUE TITLE
Cant load images !

### ISSUE THREAD

**Issue by phongnhhn92** [puzzledqs/BBox-Label-Tool#12]
Hello, I am trying to label my images but somehow I can not load images from a directory, even example images doesn't show up. Would you please help me ? 
![screenshot from 2017-05-26 11-53-51](https://cloud.githubusercontent.com/assets/11288381/26478857/2f1f214c-420a-11e7-8985-b3c64d54c0fc.png)

**Comment by puzzledqs** [comment]
Hey! You can try copying your images under ```BBox-Label-Tool-master/Images/001```, and input ```1``` into the entry.

**Comment by aurorelaurent** [comment]
Hey !

I have the same problem. Have you found a solution since?

**Comment by puzzledqs** [comment]
@aurorelaurent You can try out the solution in my previous post and see if it works for you

**Comment by Tuschristine** [comment]
After trying out the solution posted May 27th, it fixed the error, but the images still were not loading. It would return:
1
./Images/001
Any idea what's going on?

**Comment by aurorelaurent** [comment]
@Tuschristine  I have not been able to solve this problem. I used another software : labelImg and I adapted for the following

**Comment by puzzledqs** [comment]
@Tuschristine You may need to check your images' filenames. Currently only images ending with '.JPEG' are loaded. [https://github.com/puzzledqs/BBox-Label-Tool/blob/master/main.py#L134](code)

**Comment by phongnhhn92** [comment]
After reinstall my PC. I run these command and it works
`sudo apt-get install python-imaging-tk`
`sudo apt-get install python-tk`
I successfully run this program. Thanks for helping!
