### ISSUE TITLE
Why just read the original picture in /Images/001 

### ISSUE THREAD

**Issue by ljz1995** [puzzledqs/BBox-Label-Tool#16]
I have been add new picture (4.JEPG)in the /Images/001 folder, but can't load this picture .and i try to create a new folder /Images/002,and entry "2" in image Dir ,but can't load this root.
![2017-07-03 20-48-42](https://user-images.githubusercontent.com/24621291/27793532-0906ed06-6031-11e7-96f8-81b2dec0d9d9.png)

**Comment by rphly** [comment]
Rename "4.JEPG" to "4.JPEG"

**Comment by puzzledqs** [comment]
@rphly Sharp observation 👍
