### ISSUE TITLE
Pictures is too big, it cannot show all,how to  solve it? 

### ISSUE THREAD

**Issue by lijun900302** [puzzledqs/BBox-Label-Tool#17]

**Comment by pnambiar** [comment]
Has this been resolved?
I have an HD image (1920 X 1080), but I'm not able to view the entire image (Only 1396 X 935)

**Comment by puzzledqs** [comment]
A potential solution is to resize the image on-the-fly according to the monitor size, but I am not intended to implement that as I want to keep the logic as simple and clear as possible.
Nevertheless, you can always downsample your images in a pre-processing step before loading them into the label tool.

**Comment by vishank1997** [comment]
I was stuck on the same problem too. this might not work if you are working on a relatively low res screen then the data... I was working on 1080p images on a 1080p screen and by default, windows upscale the content to 125% I just turned it back to 100% and the whole image (1920 * 1080) was displayed on the tool
