### ISSUE TITLE
why does it blink when move mouse cursor over the panel?

### ISSUE THREAD

**Issue by happy15** [puzzledqs/BBox-Label-Tool#19]
Hi, I am on Macbook pro and found it keep blinking while moving mouse cursor over the panel, why?

**Comment by christophesmet** [comment]
Same issue here, can't seem to figure out them problem.

**Comment by christophesmet** [comment]
@happy15 I just noticed that if you enlarge the window the flashing stops :)

**Comment by happy15** [comment]
@christophesmet thanks for your info.
