### ISSUE TITLE
It doesn't work on windows

### ISSUE THREAD

**Issue by michael0125** [puzzledqs/BBox-Label-Tool#21]
When I run the code on windows, I encounter the following error
////////////////////////////////////////////////////////
runfile('E:/Projects/Tensorflow/BBox-Label-Tool/main.py', wdir='E:/Projects/Tensorflow/BBox-Label-Tool')
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\tensorflow\lib\tkinter\__init__.py", line 1559, in __call__
    return self.func(*args)
  File "E:/Projects/Tensorflow/BBox-Label-Tool/main.py", line 142, in loadDir
    self.category = int(s)
ValueError: invalid literal for int() with base 10: ''
////////////////////////////////////////////////////
Doesn't it work on windows?
@puzzledqs ,Could you help me solve this?

**Comment by puzzledqs** [comment]
Hi @michael0125  Thanks for using this tool.

The tool should work smoothly on Windows. For your issue, I guess you just need to copy all your images into Images/001 and input '1' before loading the images. See the [Readme](https://github.com/puzzledqs/BBox-Label-Tool/blob/master/README.md#usage) for explanations for this.

**Comment by gustavkkk** [comment]
Hi,@puzzledqs Thanks for your work.
I tested it on linux, but the same error was encountered.
I moved all my images to Images/001.
when I press "load" button, I encountered the above error.
//////////////////////////////////////////////////////////////////
    def loadDir(self, dbg = False):
        if not dbg:
            s = self.entry.get()
            self.parent.focus()
            self.category = int(s)
        else:
            s = r'D:\workspace\python\labelGUI'
/////////////////////////////////////////////////////////
where 's = self.entry.get()' returns null.
what do you think the problem is?
Thanks in advance

**Comment by puzzledqs** [comment]
@gustavkkk Did you input '1' into the textbox?

**Comment by gustavkkk** [comment]
Thanks. It works.
I thought when I press "load", 'file open' dialog shows up,then to select the directory, the selected path appears in "Image Dir" edit box.

**Comment by puzzledqs** [comment]
@gustavkkk Yes, that's what will normally expect for a common UI. 
But in our case, we had hundreds of folders to label. So specifying the numbers directly turns out easier for us :-)
