### ISSUE TITLE
error while executing main.py file

### ISSUE THREAD

**Issue by chiru83** [puzzledqs/BBox-Label-Tool#8]
test@virtualboxmachine:~/Downloads/BBox-Label-Tool-master$ python main.py
While executing this command, the following error occurred as follows:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1540, in __call__
    return self.func(*args)
  File "main.py", line 126, in loadDir
    self.category = int(s)
ValueError: invalid literal for int() with base 10: ''

Kindly help me to resolve this issue.

**Comment by zenvendof** [comment]
Try running it on Python 2.7

**Comment by chiru83** [comment]
I ran it on  Python 2.7 only and got that error. Please assist me.

Best regards

Pojala Chiranjeevi
CR/RTC1.2-IN

Tel. +91(80)6101-3423

**Comment by puzzledqs** [comment]
@chiru83 You need to put down a number (e.g., 01) in the "Image Dir" entry before loading the images.
